---
MAX_Threads: 25
MAX_CPUS: 8
scrapping_path: "./data/logs/scrapping_info.logs"
proccesing_path: "./data/logs/proccesing_info.logs"
extract_folder: "./tmp/extract/"
transform_folder: "./tmp/transform/"
...